import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { PrintQuotationButton } from "@/components/quotations/print-button";
import { requireUser } from "@/lib/auth/dal";
import { db } from "@/lib/db";
import { formatDateTime, formatMoney } from "@/modules/crm/format";
import { opportunityViewWhere } from "@/modules/crm/access";

export default async function DepositReceiptPage({ params }: { params: Promise<{ depositId: string }> }) {
  const user = await requireUser();
  const { depositId } = await params;
  const deposit = await db.deposit.findUnique({
    where: { id: depositId },
    include: {
      submittedBy: { select: { displayName: true } },
      reviewedBy: { select: { displayName: true } },
      opportunity: { include: { customer: true, owner: true } },
    },
  });
  if (!deposit) notFound();
  const allowedOpportunity = await db.opportunity.findFirst({ where: { AND: [{ id: deposit.opportunityId }, opportunityViewWhere(user)] }, select: { id: true } });
  if (!allowedOpportunity) redirect("/dashboard?error=forbidden");

  const receiptNo = deposit.reference ?? `DEP-${deposit.submittedAt.getFullYear()}-${deposit.id.slice(0, 8).toUpperCase()}`;

  return <div className="quotation-preview-page receipt-preview-page">
    <div className="preview-toolbar no-print"><Link href={`/opportunities/${deposit.opportunityId}`}>← Opportunity</Link><PrintQuotationButton /></div>
    <article className="receipt-paper">
      <header className="receipt-header">
        <div><p>NORTHSTAR PROJECTS GROUP · SALES OPERATIONS</p><h1>Deposit Receipt</h1></div>
        <div><strong>{receiptNo}</strong><span>Status: {deposit.status}</span><span>{formatDateTime(deposit.submittedAt)}</span></div>
      </header>
      <section className="receipt-grid">
        <article><span>Customer</span><strong>{deposit.opportunity.customer.name}</strong><small>{deposit.opportunity.reference}</small></article>
        <article><span>Sales owner</span><strong>{deposit.opportunity.owner.displayName}</strong><small>{deposit.opportunity.owner.email}</small></article>
        <article><span>Submitted amount</span><strong>{formatMoney(deposit.submittedAmount, deposit.currency)}</strong><small>Expected: {formatMoney(deposit.expectedAmount, deposit.currency)}</small></article>
        <article><span>CRM payment reference</span><strong>{receiptNo}</strong><small>Generated by CRM</small></article>
        <article><span>External payment reference</span><strong>{deposit.paymentReference ?? "—"}</strong><small>Bank receipt / method notes · Submitted by {deposit.submittedBy.displayName}</small></article>
      </section>
      <section className="receipt-status-panel">
        <h2>Finance confirmation</h2>
        <p>{deposit.status === "CONFIRMED" ? "Finance confirmed this deposit. The opportunity can be marked Won by the workflow." : "This deposit receipt is waiting for Finance confirmation before the opportunity becomes Won."}</p>
        <dl>
          <div><dt>Reviewed by</dt><dd>{deposit.reviewedBy?.displayName ?? "—"}</dd></div>
          <div><dt>Reviewed at</dt><dd>{formatDateTime(deposit.reviewedAt)}</dd></div>
          <div><dt>Review notes</dt><dd>{deposit.reviewNotes ?? "—"}</dd></div>
        </dl>
      </section>
      <footer className="receipt-signatures"><div><span>Sales / Submitted by</span><i /><strong>{deposit.submittedBy.displayName}</strong></div><div><span>Finance approval</span><i /><strong>{deposit.reviewedBy?.displayName ?? "Pending"}</strong></div></footer>
    </article>
  </div>;
}
